[package]
authors = [
    "Sean Bowe <ewillbefull@gmail.com>",
    "Eirik Ogilvie-Wigley <eowigley@gmail.com>",
    "Jack Grigg <thestr4d@gmail.com>",
]
description = "Implementation of the Jubjub elliptic curve group"
documentation = "https://docs.rs/jubjub/"
homepage = "https://github.com/zkcrypto/jubjub"
license = "MIT/Apache-2.0"
name = "jubjub"
repository = "https://github.com/zkcrypto/jubjub"
version = "0.6.0"
edition = "2018"

[dependencies.bitvec]
version = "0.22"
default-features = false

[dependencies.bls12_381]
version = "0.4"
default-features = false

[dependencies.ff]
version = "0.9"
default-features = false

[dependencies.group]
version = "0.9"
default-features = false

[dependencies.rand_core]
version = "0.6"
default-features = false

[dependencies.subtle]
version = "^2.2.1"
default-features = false

[dev-dependencies]
criterion = "0.3"

[dev-dependencies.rand_xorshift]
version = "0.3"
default-features = false

[features]
default = ["alloc"]
alloc = ["group/alloc"]
bits = ["ff/bits"]

[[bench]]
name = "fq_bench"
harness = false

[[bench]]
name = "fr_bench"
harness = false

[[bench]]
name = "point_bench"
harness = false

[patch.crates-io]
bls12_381 = { git = "https://github.com/nuttycom/bls12_381.git", branch = "bitvec-0.22", default-features = false }
ff = { git = "https://github.com/zkcrypto/ff.git", branch = "main", default-features = false }
group = { git = "https://github.com/zkcrypto/group.git", branch = "main", default-features = false }
